version: "3.2"
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'admin'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
